version: "3"

services:
  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5002:3000
    volumes:
      - ./code/data:/app/data
    