version: "3"

services:
  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:5002
    volumes:
      - ./code/data:/app/data
    