version: "3"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data/downloadedVideos:/app/downloadedVideos
      - ./data/tmp:/app/tmp
      - ./data/channels.txt:/app/channels.txt
      - ./data/downloaded.txt:/app/downloaded.txt
      - ./data/waitlist.txt:/app/waitlist.txt